# Site settings
title: Hari Gurumoorthi
description: Hari Knowledge bits
baseurl: # "/harigurumoorthi.page" # the subpath of your site, e.g. /blog
url: "https://harigurumoorthi.page"
enforce_ssl: harigurumoorthi.page
# repository: YoussefRaafatNasry/portfolYOU
remote_theme: YoussefRaafatNasry/portfolYOU

# Build settings
markdown: kramdown
# plugins:
# - jekyll-feed


# Author Info
author:
  name     : Hari
  image    : assets/hari-profile.jpg
  email    : hari.gurumoorthi@gmail.com
  github   : hariguru
  twitter  : tweetofhari
  linkedin : https://www.linkedin.com/in/harigurumoorthi/
#  facebook : username


# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name


# Default values for collections
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"


# Posts default Permalink
permalink: articles/:title


# Exclude from processing.
exclude:
- README.md
- CONTRIBUTING.md
- LICENSE
- Gemfile
- Gemfile.lock
